### ISSUE TITLE
Custom weights - error incorrect number of dimensions

### ISSUE THREAD

**Issue by 03rcooke** [fitzLab-AL/gdm#27] opened 2022-07-07 14:26 UTC
I would like to use the custom weights option of the `formatsitepair` function. However the code produces the error: `Error in custWeights[, "gettingCoolSiteColumn"][, 1] : incorrect number of dimensions`. I think the offending line is `hwap <- custWeights[, "gettingCoolSiteColumn"][, 1]`, which seems to incorrectly subset the custom weights data.frame (unless I've incorrectly set up the custom weights data.frame). Here's a reproducible example:
```r
# set up data
sppData <- southwest[c(1,2,13,14)]
envTab <- southwest[c(2:ncol(southwest))]

# create custom weights data.frame
custw <- data.frame(site = unique(sppData$site), weights = runif(length(unique(sppData$site))))

# run format site pair
sitePairTab <- formatsitepair(sppData, 2, XColumn = "Long", YColumn = "Lat", sppColumn = "species", 
siteColumn = "site", predData = envTab, weightType = "custom", custWeights = custw, verbose = TRUE)
```
Best,
Rob

**Comment by fitzLab-AL** [comment] 2022-08-03 19:28
Yes, it looks like the problem is with the line you identified. I will fix the code & push the version of the package to the repo soon.

Thanks-

**Comment by fitzLab-AL** [comment] 2022-08-03 19:47
Should be fixed now - let me know if you have further issues.

**Closed as completed by fitzLab-AL** 2022-08-03 19:47 UTC

**Comment by 03rcooke** [comment] 2022-08-10 15:33
Thanks! Works perfectly!

Best,
Rob
